#!/bin/sh

set -e

propane=~/Library/Application\ Support/Propane

if [[ ! -d $propane ]]; then echo -n "U moron, first install and open Propane" && exit; fi

if [[ -d "$propane/styles" ]]; then rm -Rf "$propane/styles"; fi
if [[ -d "$propane/unsupported" ]]; then rm -Rf "$propane/unsupported"; fi

ln -s /my/dev/chicisimo/propane-theme/styles "$propane"
ln -s /my/dev/chicisimo/propane-theme/unsupported "$propane"
